# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=10)),
                ('portrait', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('qq', models.CharField(max_length=20)),
                ('tele', models.CharField(max_length=15)),
            ],
        ),
    ]
